### PR TITLE
Fix JAVA_HOME

### PR DESCRIPTION
**Pull request by brunoborges**
Fixes issue #11 .

### CODE REVIEW

**Comment by shrishrirang** [comment]
Thanks @brunoborges for the PR, the change looks pretty good.

I'm going to leave the PR open for a while, because we are expecting Azul to define `JAVA_HOME` in the base images, so that we don't have to update these values every time we roll out a newer version.

**Comment by brunoborges** [comment]
@shrishrirang, any chance this can be fixed for the current version we have on? Some Java frameworks and runtimes do rely on $JAVA_HOME to be properly set up, even or Java SE runtime.

**Comment by shrishrirang** [comment]
Yes, I am working on rolling out a fix soon.

**Comment by shrishrirang** [comment]
@brunoborges : As part of a set of improvements we are doing to the image, we fixed this issue with this commit: https://github.com/Azure-App-Service/java/pull/15/commits/ae897db7cf804e7ee830890496d9a3f9ace5dc4c. `JAVA_HOME` is now defined by the base image.

This has taken a little longer than expected, thanks for waiting. We'll be updating the official image in the next couple days.

**Pull request closed without merging**
