### PR TITLE
Copy wwwroot to /local before running the app

### PR DESCRIPTION
**Pull request by shrishrirang**
- Copy wwwroot to a local location before running the app
- Skip local copying of the application if WEBSITE_SKIP_LOCAL_COPY is set to 1 or true (case insensitive) or if Local cache is enabled (in which case copying the app again is unnecessary)
- Also, enable case-insensitive string comparisons at the very beginning in init_container.sh

### CODE REVIEW

**Comment by shrishrirang** [comment]
@jvano

**Review by jvano — APPROVED** [review]
:shipit:

**Comment by shrishrirang** [comment]
@jvano - minor change.

**Comment by jvano** [comment]
Yeah, it looks good!

**Pull request merged**
